spring:
    redis:
        host: 127.0.0.1
        port: 6379
        database: 8


    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: 123456
        username: root
        url: jdbc:mysql://localhost:3306/short-url
        druid:
            initial-size: 1
            min-idle: 1
            max-active: 20
            test-on-borrow: true

