version: '3.8'
services:

  secuity-jwt-demo:
    image: liuli20061014docker/security-jwt-demo:1.0
    ports:
      - "8080:8080"
    environment:
      PROFILE: "dev"
      SERVER_PORT: "8080"
      mysql.username: root
      mysql.password: 123456
      mysql.host: 192.168.126.131
      mysql.port: 3306
      redis.port: 6379
      redis.host: 192.168.126.131



