server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    druid:
      driver-class-name:  com.mysql.jdbc.Driver
      username: root
      password: 123456
      url:  jdbc:mysql://localhost:3306/spring_security
      max-active: 10
      min-idle: 5
      max-wait:  -1
