spring:
  profiles:
    active: pro

mybatis-plus:
  mapper-locations:
    - classpath*:META-INF/mybatis/mapper/**/*.xml
  config-location: classpath:META-INF/mybatis/mybatis-config.xml

logging:
  level.org.springframework.security: debug