---  单位时间内（每秒、每分钟内）请求次数限流
--- Generated by Luanalysis
--- Created by Administrator.
--- DateTime: 2021-9-12 下午 10:41
---

-- 定义限流的方法签名
local methodKey=KEYS[1]

-- 调用脚本传入的限流大小
local limit = tonumber(ARGV[1])

redis.log(redis.LOG_NOTICE,'the max request limit is '.. limit)

--调用脚本传入的限流时间单位
local timeunit = ARGV[2]

-- 调用前的流量大小,第一次为空，则给0
local count = tonumber(redis.call('get', methodKey)  or  "0");
redis.log(redis.LOG_NOTICE,'the request count is '.. count)

-- 是否超出限流阀值
if count + 1 > limit then
    -- 拒绝服务访问
    return false;
else
    -- 没有超出阀值
    -- 设置当前访问的次数 +1
    redis.call('INCRBY', methodKey, 1)

    -- 设置过期时间
    if (timeunit=="SECONDS") then
        -- 过期时间设置为1秒
        redis.call('EXPIRE', methodKey,1);
    elseif(timeunit=="MINUTES") then
        -- 过期时间设置为1分钟
        redis.call('EXPIRE', methodKey,1*60);
    end
    return true;
end
