spring:
  profiles:
    active: prod
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dbgirl
    username: root
    password: 123456
    druid:
      max-wait: -1  #获取连接不超时，一直等

  redis:
    host: localhost
    port: 6379
    database: 0

  cache:
    type: REDIS
    redis:
      use-key-prefix: true
      time-to-live: 360000
      cache-null-values: true

  aop:
    proxy-target-class: true    #Springboot2.0默认使用CGLIB动态代理

    #  task:
    #    scheduling:
    #      pool:
    #        size: 5


  main:
    allow-bean-definition-overriding: true
  task:
    execution:
      pool:
        core-size: 8
        max-size: 8

  cloud:
    sentinel:
      transport:
        dashboard: localhost:8088
        port: 8197
        heartbeatIntervalMs: 500
      filter:
        enabled: true
      eager: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: ERROR


mybatis-plus:
  mapper-locations:
    - classpath*:META-INF/mybatis/mapper/**/*.xml
  config-location: classpath:META-INF/mybatis/mybatis-config.xml


server:
  tomcat:
    max-connections: 8192  #最大连接数，超过最大连接数 + 等待队列长度的请求直接拒绝
    accept-count: 100   #超过最大连接数后，等待队列长度
    threads:
      max: 200   #最大并发请求数，同一时刻能处理的最大请求数，当处理完请求后，从请求连接中又并发处理200，直到所有连接请求处理完毕
      min-spare: 10