spring:
  profiles:
    active: prod
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dbgirl
    username: root
    password: 123456

   ##每次都重新建立表，可以再第一时使该参数，后续用使用update
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true





  
  
  
