server:
  port: 8081
  context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shiro
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource


  #spring.datasource.druid.initial-size=1
  #spring.datasource.druid.min-idle=1
  # spring.datasource.druid.max-active=20
  #spring.datasource.druid.test-on-borrow=true
  # spring.datasource.druid.stat-view-servlet.allow=true


  redis:
    host: localhost
    port: 6379


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.liul.shiro.po
  configuration:
    map-underscore-to-camel-case: true
    type-handlers-package: com.liul.shiro.mybatis

shiro:
  loginUrl: /login.html
  # userNativeSessionManager: true
  #unauthorizedUrl: /error.html

logging:
  level: debug









